---
title: "Meadoway Analysis: Data Cleaning"
author: "Garland Xie"
date: "05/01/2021"
output: html_document
---

# Load libraries 

```{r libraries}
library(readxl)
library(here)
library(janitor)
library(dplyr)
library(tidyr)
library(purrr)
```

# Import 

```{r get list files}

files_2016_mv <- 
  list.files(
    here("data/original"),
    pattern = "2016"
    )

files_2018_mv <-
  list.files(
    here("data/original"), 
    pattern = "2018"
    )

files_2019_mv <- 
  list.files(
    here("data/original"), 
    pattern = "2019"
    )

```

```{r import custom functions}
source(here("src", "functions.R"))
```

```{r import 2016 data }

mv_2016_cover <- 
  bind_rows(
    map(files_2016_mv, 
        import_2016_data)
    )

```

```{r import 2018 data}

mv_2018_cover_spr <- 
  bind_rows(
    map(files_2018_mv, 
        import_data_spring)
    )

mv_2018_cover_sum <- 
  bind_rows(
    map(files_2018_mv, 
        import_data_summer)
    )

```

```{r import 2019 data}

mv_2019_cover_spr <- 
  bind_rows(
    map(files_2019_mv, 
        import_data_spring)
    )

mv_2019_cover_sum <- 
  bind_rows(
    map(files_2019_mv, 
        import_data_summer)
    )

```

# Data cleaning 

```{r clean 2016 data}

cover_2016_tidy <- 
  
  # select appropriate columns
  mv_2016_cover %>%
  select(
    year, 
    season,
    site,
    quadrat,
    spp,
    cover,
    solitary
  ) %>%
  
  # clean up the cover data 
  mutate(
    
    cover = case_when(
      cover == "<1" ~ "0.5",
      TRUE ~ cover),
    
    cover = as.numeric(cover)
  ) %>%
  
   # remove empty rows (with missing values)
  filter(!is.na(spp),
         !is.na(cover)
         )

```

```{r clean 2018 data}

cover_2018_tidy <-
  mv_2018_cover_spr %>%
  
  # get both summer and spring data
  bind_rows(mv_2018_cover_sum) %>%
  
  # select appropriate columns
  select(
    year, 
    season,
    site,
    quadrat,
    spp,
    cover,
    solitary) %>%
  
  # clean data for cover column
  mutate(
  
    cover = case_when(
      cover == "<1" ~ "0.5",
      cover == "Seedlings." ~ "0.5",
      TRUE ~ cover),
    
    cover = na_if(cover, "NA"),
    cover = as.numeric(cover)
  ) %>%
  
  # remove empty rows (with missing values)
  filter(!is.na(spp),
         !is.na(cover))

```

```{r clean 2019 data}

cover_2019_tidy <-
  mv_2019_cover_spr %>%
  
  # get both summer and spring data
  bind_rows(mv_2019_cover_sum) %>%
  
  # select appropriate columns
  select(
    year, 
    season,
    site,
    quadrat,
    spp,
    cover,
    solitary) %>%
  
  # clean data for cover column
  mutate(
    cover = case_when(
      cover == "<1" ~ "0.5", 
      TRUE ~ cover),
    
    cover = as.numeric(cover)
  )  %>%
  
  # remove empty rows (with missing values)
  filter(!is.na(spp),
         !is.na(cover),
         spp != "NA"
         )

```

```{r row bind 2016-2019 data}
cover_tidy <- bind_rows(
  cover_2016_tidy, 
  cover_2018_tidy, 
  cover_2019_tidy
)
```

# Save the data 

```{r save the data!}
write.csv(
  x = cover_tidy, 
  file = here("data/final", "cover_tidy.csv"),
  row.names = FALSE
)
```

