---
title: 'Meadoway Analysis: EDA'
author: "Garland Xie"
date: "07/01/2021"
output: html_document
---

# Libraries 

```{r libraries}
library(here)
library(ggplot2)
library(dplyr)
library(purrr)
```
# Import

```{r read csv data}
cover_df <- read.csv(
  here("data/final", "cover_tidy.csv"),
  stringsAsFactors = FALSE
)
```

```{r import custom functions}
source(here("src", "functions.R"))
```

# Check packaging 

```{r sanity checks}
str(cover_df)
head(cover_df, n = 10)
tail(cover_df, n = 10)
```

# Species code 

```{r data clean: species code}
spp_code <- 
  cover_df %>%
  mutate(
    
    spp_code = map_chr(spp, get_spp_code),
    
    spp_code = case_when(
      spp == "Ambrosia artemisiifolia" ~ "AMBAR",
      spp == "Lepidium campestre" ~ "LEPCA",
      spp == "Tragopogon pratensis" ~ "TRAPA",
      TRUE ~ spp_code),
    
    # fix a typo
    spp = case_when(
      spp == "thatch" ~ "Thatch",
      TRUE ~ spp)
    
  )
```

# Sites: A to F (Seed Mix 1)

```{r freq CYR (A to F), fig.height=4, fig.width=7, message=FALSE}

# Sites A to F
ls_A_F <- paste0("24", LETTERS[1:6])

spp_code %>%
  filter(spp_code == "CYRO",
         site %in% ls_A_F) %>%
  group_by(year, season, site) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x = site, y = frequency)) +
  geom_point() +
  geom_hline(yintercept = 3, linetype = "dashed") +
  facet_wrap(year~season, ncol = 5, nrow = 1) +
  labs(x = NULL, y = "Frequency of CYRO") +
  coord_flip() +
  theme_bw()
```

```{r cover CYRO: Sites A to F, message=FALSE}

# Sites A to F
ls_A_F <- paste0("24", LETTERS[1:6])

ab_CYRO <- spp_code %>%
  filter(
    site %in% ls_A_F &
    spp_code == "CYRO"
  ) %>%
  mutate(quadrat = as.character(quadrat),
         year = as.character(year))

ab_CYRO %>%
  ggplot(aes(x = year, y = cover, group = quadrat, col = quadrat)) +
  geom_point() + 
  geom_line() + 
  labs(
    title = "Seed Mix 1",
    x = "Year", 
    y = "Absolute cover (%) of CYRO"
    ) + 
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8, 10)) +
  facet_wrap(season~site, nrow = 2, ncol = 6) + 
  theme_bw() 
```
```{r SR (excl CYRO): Sites A to F, message=FALSE}

# Sites A to F
ls_A_F <- paste0("24", LETTERS[1:6])
  
sr_df <- spp_code %>%
  filter(spp_code != "CYRO",
         site %in% ls_A_F,
         !(spp_code %in% c("BASO", "THNA", "MONA"))) %>%
  mutate(
    year = as.character(year),
    quadrat = as.character(quadrat)) %>%
  group_by(year, season, site, quadrat) %>%
  summarize(
    sr = length(unique(spp))
  ) 

# Keep in mind that there's no data for spring 2016 

sr_df %>%
  ggplot(aes(x = year, y = sr, group = quadrat, color = quadrat)) +
  geom_line(position = position_jitter(w = 0.02, h = 0)) + 
  geom_hline(yintercept = 10, linetype = "dashed") + 
  facet_wrap(season~site, nrow = 2, ncol = 6) +
  labs(
    title = "Seed Mix 1", 
    x = "Year", 
    y = "Species Richness (excluding CYRO)"
    ) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

# Sites: M to O (Seed Mix 1)

```{r freq CYR: M to O, fig.height=4, fig.width=7}

# Sites A to O 
ls_MNO <- paste0("24", c("M", "N", "O"))

# Keep in mind that there's no data for spring 2016
spp_code %>%
  filter(spp_code == "CYRO",
         site %in% ls_MNO) %>%
  group_by(year, season, site) %>%
  summarize(frequency = n()) %>%
  mutate(year = as.character(year)) %>%
  ggplot(aes(x = year, y = frequency, group = site, color = site)) +
  geom_point() +
  geom_line() + 
  labs(x = NULL, y = "Frequency of CYRO") +
  facet_wrap(~season) + 
  theme_bw()
  
```
```{r cover CYRO: Sites M to O, message=FALSE}

# Sites M to O

ls_MNO <- paste0("24", c("M", "N", "O"))

ab_CYRO <- spp_code %>%
  filter(
    site %in% ls_MNO &
    spp_code == "CYRO"
  ) %>%
  mutate(quadrat = as.character(quadrat),
         year = as.character(year))

# Keep in mind that there's no 2016 data 

ab_CYRO %>%
  ggplot(aes(x = year, y = cover, group = quadrat, col = quadrat)) +
  geom_point() + 
  geom_line() + 
  labs(
    title = "Seed Mix 1",
    x = "Year", 
    y = "Absolute cover (%) of CYRO"
    ) + 
  scale_y_continuous(breaks = c(0, 2, 4, 6, 8, 10)) +
  facet_wrap(season~site, nrow = 2, ncol = 3) + 
  theme_bw() 
```

```{r SR (excl CYRO): Sites M to O, message=FALSE}

# Sites M to O
ls_MNO <- paste0("24", c("M", "N", "O"))
  
sr_MNO <- spp_code %>%
  filter(spp_code != "CYRO",
         site %in% ls_MNO,
         !(spp_code %in% c("BASO", "THNA", "MONA"))) %>%
  mutate(
    year = as.character(year),
    quadrat = as.character(quadrat)) %>%
  group_by(year, season, site, quadrat) %>%
  summarize(
    sr = length(unique(spp))
  ) 

# Keep in mind that there's no data for spring 2016 

sr_MNO %>%
  ggplot(aes(x = year, y = sr, group = quadrat, color = quadrat)) +
  geom_line(position = position_jitter(w = 0.02, h = 0)) + 
  geom_hline(yintercept = 10, linetype = "dashed") + 
  facet_wrap(season~site, nrow = 2, ncol = 3) +
  labs(
    title = "Seed Mix 1", 
    x = "Year", 
    y = "Species Richness (excluding CYRO)"
    ) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))


```

# Sites: G to L (Seed Mix 2)

```{r freq CYR: G to L, fig.height=4, fig.width=7}

# Sites G to L
ls_G_L <- paste0("24", LETTERS[7:12])

spp_code %>%
  filter(spp_code == "CYRO",
         site %in% ls_G_L) %>%
  group_by(year, season, site) %>%
  summarize(frequency = n()) %>%
  ggplot(aes(x = site, y = frequency)) +
  geom_point() +
  geom_hline(yintercept = 3, linetype = "dashed") +
  facet_wrap(year~season, ncol = 5, nrow = 1) +
  labs(x = NULL, y = "Frequency of CYRO") +
  coord_flip() +
  theme_bw()
  
```

```{r cover CYRO: Sites G to L, message=FALSE}

# Sites M to O
ls_G_L <- paste0("24", LETTERS[7:12])

ab_CYRO_GL <- spp_code %>%
  filter(
    site %in% ls_G_L &
    spp_code == "CYRO"
  ) %>%
  mutate(quadrat = as.character(quadrat),
         year = as.character(year))

ab_CYRO_GL %>%
  ggplot(aes(x = year, y = cover, group = quadrat, col = quadrat)) +
  geom_point() + 
  geom_line() + 
  labs(
    title = "Seed Mix 2",
    x = "Year", 
    y = "Absolute cover (%) of CYRO"
    ) + 
  facet_wrap(season~site, nrow = 2, ncol = 5) + 
  theme_bw() 

```


```{r SR (excl CYRO): Sites G to L, message=FALSE}

# Sites G to L

ls_G_L <- paste0("24", LETTERS[7:12])
  
sr_GL <- spp_code %>%
  filter(spp_code != "CYRO",
         site %in% ls_G_L,
         !(spp_code %in% c("BASO", "THNA", "MONA"))) %>%
  mutate(
    year = as.character(year),
    quadrat = as.character(quadrat)) %>%
  group_by(year, season, site, quadrat) %>%
  summarize(
    sr = length(unique(spp))
  ) 

# Keep in mind that there's no data for spring 2016 

sr_GL %>%
  ggplot(aes(x = year, y = sr, group = quadrat, color = quadrat)) +
  geom_line(position = position_jitter(w = 0.02, h = 0)) + 
  geom_hline(yintercept = 10, linetype = "dashed") + 
  facet_wrap(season~site, nrow = 2, ncol = 6) +
  labs(
    title = "Seed Mix 1", 
    x = "Year", 
    y = "Species Richness (excluding CYRO)"
    ) + 
  theme_bw() + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

```

# Other Stuff

```{r 2016: sites A to O, fig.height=6, fig.width=6, message=FALSE}

# show plots with CYRO cover (highlights)

plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24A")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24B")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24D")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24F")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24G")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24H")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24I")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24K")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24L")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24M")
plot_cover_site_year(df = spp_code, yr = "2016", sn = "Summer", s = "24N")
```

```{r 2018: sites A to O, fig.height=6, fig.width=6, message=FALSE}

# show plots with CYRO cover (highlights)
# sites A to O

plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24A")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24B")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24D")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24F")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24G")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24H")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24I")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24K")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24L")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24M")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24N")
plot_cover_site_year(df = spp_code, yr = "2018", sn = "Summer", s = "24O")

```

```{r 2019: sites A to O, fig.height=6, fig.width=6, message=FALSE}
# show plots with CYRO cover (highlights)
# sites A to O

plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24A")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24B")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24C")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24D")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24E")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24F")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24G")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24H")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24I")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24K")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24L")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24M")
plot_cover_site_year(df = spp_code, yr = "2019", sn = "Summer", s = "24O")

```
